repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
  - repo: local
    hooks:
      - id: feature-matrix-generate
        name: feature-matrix-generate
        entry: tool/precommit/generate.sh
        language: system
        pass_filenames: false
        files: ^feature_matrix\.yaml$
