# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - gofmt
    - goimports
    - gosec
    - misspell
    - unconvert
    - whitespace
