openapi: 3.1.0
info:
  title: AshTrail API
  version: 0.1.0
servers:
  - url: https://api.example.com
paths:
  /v1/items:
    get:
      summary: List items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      required: [id, name]
      properties:
        id:
          type: string
        name:
          type: string
