name: Feature Matrix Diff

on:
  pull_request:
    paths:
      - 'feature_matrix.yaml'

jobs:
  diff:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run diff script
        id: diff
        run: |
          python scripts/diff_feature_matrix.py > diff.md
          echo 'diff<<EOF' >> $GITHUB_OUTPUT
          cat diff.md >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const existing = await github.paginate(github.rest.issues.listComments, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              per_page: 100
            });
            const marker = '<!-- feature-matrix-diff -->';
            for (const c of existing) {
              if (c.user.type === 'Bot' && c.body && c.body.includes(marker)) {
                await github.rest.issues.deleteComment({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  comment_id: c.id
                });
              }
            }
            const diff = `${marker}\n${{ steps.diff.outputs.diff }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: diff,
            });
