name: Generate Artifacts

on:
  push:
    paths:
      - 'feature_matrix.yaml'
      - 'scripts/**'
  pull_request:
    paths:
      - 'feature_matrix.yaml'
      - 'scripts/**'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests jsonschema

      - name: Validate feature_matrix schema
        run: |
          python -c "import json,yaml,jsonschema,pathlib;d=yaml.safe_load(pathlib.Path('feature_matrix.yaml').read_text(encoding='utf-8'));s=json.loads(pathlib.Path('tool/json_schema/feature_matrix.schema.json').read_text(encoding='utf-8'));jsonschema.validate(d,s);print('Schema validation OK')"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Run generator
        run: python scripts/generate_from_feature_matrix.py

      - name: Run build_runner (Freezed)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: |
          if [ -d test ] && [ "$(ls -A test)" ]; then
            flutter test --coverage
          fi

      - name: Check for uncommitted changes
        run: |
          git add .
          if ! git diff --cached --quiet; then
            echo 'ERROR: Generated artifacts not committed.'
            git diff --cached --name-only
            exit 1
          fi

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
