name: Nightly Coverage

on:
  schedule:
    - cron: '0 4 * * *' # Daily at 04:00 UTC
  workflow_dispatch: {}

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.2'
      - name: Run tests with coverage
        run: |
          flutter pub get
          flutter test --coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: coverage/lcov.info
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage/lcov.info
          flags: nightly
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: false
